version: '2'
services:
  agent-infra:
    image: newrelic/infrastructure:1.2.25
    environment:
      NRIA_LICENSE_KEY: ${NRIA_LICENSE_KEY}
      NRIA_CUSTOM_ATTRIBUTES: ${NRIA_CUSTOM_ATTRIBUTES}
      {{- if eq .Values.PROXY "true"}}
      http_proxy: ${HTTP_PROXY}
      https_proxy: ${HTTPS_PROXY}
      no_proxy: ${NO_PROXY}
      {{- end}}
    network_mode: host
    cap_add:
      - SYS_PTRACE
    volumes:
      - /:/host:ro
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.global: ${GLOBAL_SERVICE}
      io.rancher.container.hostname_override: container_name
      {{- if (.Values.AFFINITY_HOST_LABEL)}}
      io.rancher.scheduler.affinity:host_label: ${AFFINITY_HOST_LABEL}
      {{- end}}
    logging:
      driver: json-file
      options:
        max-size: 100M
        max-file: '5'
    security_opt:
      - apparmor:unconfined
