version: '2'
catalog:
  name: "newrelic"
  version: "1.2.25"
  questions:
    - variable: "NRIA_LICENSE_KEY"
      label: "New Relic Licence Key"
      description: "Licence key provided by New Relic."
      required: true
      type: "string"
    - variable: "GLOBAL_SERVICE"
      label: "Run service globally?"
      description: "Always run one instance of this service on every host.  Set false to allow manual/other scaling"
      required: true
      type: "boolean"
      default: "true"
    - variable: "AFFINITY_HOST_LABEL"
      label: "Host Affinity"
      description: "Control the hosts on which the agent runs. Will run globally if left blank."
      required: false
      type: "string"
      default: "newrelic-infra=true"
    - variable: PROXY
      description: "If New Relic needs to access the outside world via a proxy select true."
      label: "Proxy Required?"
      required: true
      type: boolean
      default: "false"
    - variable: HTTP_PROXY
      description: "Leave blank if proxy is not required, otherwise set http proxy URL eg http://<proxy>:<port>/"
      label: "HTTP Proxy URL"
      required: false
      type: "string"
    - variable: HTTPS_PROXY
      description: "Leave blank if proxy is not required, otherwise set https proxy URL eg https://<proxy>:<port>/"
      label: "HTTPS Proxy URL"
      required: false
      type: "string"
    - variable: NO_PROXY
      description: "Leave blank if proxy is not required, otherwise set no proxy domains eg 127.0.0.1,localhost,test.domain.com"
      label: "No Proxy Settings"
      required: false
      type: "string"
    - variable: "NRIA_CUSTOM_ATTRIBUTES"
      description: 'Leave blank if no custom attributes, otherwise of form {"attribute1":"value1", "attribute2":"value2"}'
      label: "Custom Attributes"
      required: false
      type: "string"
services:
  agent-infra:
    scale: 1
    start_on_create: true
