version: '2'
services:
  azdisk-driver:
    privileged: true
    network_mode: host
    image: industrieco/storage-azdisk:v0.1.3
    labels:
      io.rancher.scheduler.global: 'true'
      io.rancher.container.create_agent: 'true'
      io.rancher.container.agent.role: environment
    environment:
      AZURE_SUBSCRIPTION: '${AZURE_SUBSCRIPTION}'
      AZURE_USERNAME: '${AZURE_USERNAME}'
      AZURE_PASSWORD: '${AZURE_PASSWORD}'
      AZURE_TENANT_ID: '${AZURE_TENANT_ID}'
      AZURE_SERVICE_PRINCIPAL: '${AZURE_SERVICE_PRINCIPAL}'
      RANCHER_DEBUG: '${RANCHER_DEBUG}'
    volumes:
    - /run:/run
    - /var/run:/var/run
    - /dev:/host/dev
    - /var/lib/rancher/volumes:/var/lib/rancher/volumes:shared
    logging:
      driver: json-file
      options:
        max-size: 25m
        max-file: '2'
