version: '2'
{{- if ne .Values.volume_type "named"}}
volumes:
  graylog-elasticsearch-volume:
    driver_opts:
      device: ${volume_mnt_src}/elasticsearch/data
      o: bind
      type: none
{{-end}}
services:
  mongo:
    image: "mongo:3.6.2"
    volumes:
      {{- if eq .Values.volume_type "named"}}
      - graylog-mongo-volume:/data/db
      {{- else}}
      - ${volume_mnt_src}/mongo/data/db:/data/db
      {{- end}}
    {{- if ne .Values.mongodb_host_label "" }}
    labels:
      io.rancher.scheduler.affinity:host_label: ${mongodb_host_label}
    {{- end}}
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.2
    stdin_open: true
    tty: true
    environment:
      cluster.name: graylog
      bootstrap.memory_lock: true
      discovery.type: single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - graylog-elasticsearch-volume:/usr/share/elasticsearch/data
    labels:
      io.rancher.container.pull_image: always
      {{- if ne .Values.elasticsearch_host_label "" }}
      io.rancher.scheduler.affinity:host_label: ${elasticsearch_host_label}
      {{- end}}
      io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
  kopf:
    image: lmenezes/elasticsearch-kopf:2.1.2
    environment:
      KOPF_ES_SERVERS: elasticsearch:9200
      KOPF_SERVER_NAME: _
    links:
      - elasticsearch:elasticsearch
    {{- if ne .Values.elasticsearch_port "" }}
    ports:
      - ${elasticsearch_port}:80
    {{- end}}
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
      {{- if ne .Values.kopf_host_label "" }}
      io.rancher.scheduler.affinity:host_label: ${kopf_host_label}
      {{- end}}
  graylog:
    image: "industrieco/graylog:2.4.1-2"
    stdin_open: true
    tty: true
    environment:
      TZ: ${graylog_timezone}
      GRAYLOG_ROOT_TIMEZONE: ${graylog_timezone}
      GRAYLOG_ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      GRAYLOG_PASSWORD_SECRET: ${graylog_secret}
      GRAYLOG_ROOT_PASSWORD_SHA2: ${graylog_password}
      GRAYLOG_WEB_ENDPOINT_URI: "${graylog_url}"
    labels:
      io.rancher.sidekicks: geoip-data
      {{- if ne .Values.graylog_server_host_label "" }}
      io.rancher.scheduler.affinity:host_label: ${graylog_server_host_label}
      {{- end}}
      io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    volumes:
      {{- if eq .Values.volume_type "named"}}
      - graylog-journal-volume:/usr/share/graylog/data/journal
      {{- else}}
      - ${volume_mnt_src}/graylog/data/journal:/usr/share/graylog/data/journal
      {{- end}}
    volumes_from:
      - geoip-data
    links:
      - elasticsearch:elasticsearch
      - mongo:mongo
    ports:
    {{- if ne .Values.graylog_port "" }}
      - ${graylog_port}:9000
    {{- end}}
      - 12201:12201/udp
      - 12201:12201/tcp
      - 1514:1514/udp
  geoip-data:
    image: tkrs/maxmind-geoipupdate
    stdin_open: true
    tty: true
    volumes:
      {{- if eq .Values.volume_type "named"}}
      - graylog-geodata-volume:/usr/share/graylog/data/geoip
      {{- else}}
      - ${volume_mnt_src}/geoip:/usr/share/graylog/data/geoip
      {{- end}}
    environment:
      GEOIP_DB_DIR: '/usr/share/graylog/data/geoip/'
      {{- if ne .Values.https_proxy "" }}
      https_proxy: ${https_proxy}
      {{- end}}
    labels:
      io.rancher.container.pull_image: always
{{- if eq .Values.enable_logspout "true" }}
  logspout:
    image: flaccid/logspout:gelf
    stdin_open: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    tty: true
    environment:
      INACTIVITY_TIMEOUT: 1m
    command:
      - "gelf://graylog:12201"
    links:
      - graylog:graylog
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.global: 'true'
{{- end }}
