version: '2'
services:
{{- if eq .Values.RANCHER_URL "" }}
  cadvisor:
    labels:
      io.rancher.scheduler.global: 'true'
    tty: true
    image: google/cadvisor:latest
    stdin_open: true
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:rw"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"

  node-exporter:
    labels:
      io.rancher.scheduler.global: 'true'
    tty: true
    image: prom/node-exporter:latest
    stdin_open: true
{{- end}}

  prom-conf:
    tty: true
    image: industrieco/prom-conf:i1
    volumes:
      - /etc/prom-conf/
    environment:
      - DISCOVERY={{- if eq .Values.RANCHER_URL "" }}false{{- else}}true{{- end}}
    labels:
      io.rancher.container.start_once: 'true'

{{- if ne .Values.RANCHER_URL "" }}
  prom-rancher-discovery:
    tty: true
    image: industrieco/prom-rancher-discovery:latest
    volumes_from:
      - prom-conf
    environment:
      RANCHER_URL: ${RANCHER_URL}
      RANCHER_ACCESS_KEY: ${RANCHER_ACCESS_KEY}
      RANCHER_SECRET_KEY: ${RANCHER_SECRET_KEY}
      NODE_PORT: 9104
      CADVISOR_PORT: 9103
{{- end}}

  prometheus:
    tty: true
    image: prom/prometheus:v1.6.0
    command: -alertmanager.url=http://alertmanager:9093 -config.file=/etc/prom-conf/prometheus.yml -storage.local.path=/prometheus -web.console.libraries=/etc/prometheus/console_libraries -web.console.templates=/etc/prometheus/consoles
    {{- if ne .Values.PROMETHEUS_PORT "" }}
    ports:
      - ${PROMETHEUS_PORT}:9090
    {{- end}}
    labels:
      io.rancher.sidekicks: prom-conf{{- if ne .Values.RANCHER_URL "" }},prom-rancher-discovery{{- end}}
      {{- if ne .Values.PROMETHEUS_HOST_LABEL "" }}
      io.rancher.scheduler.affinity:host_label: ${PROMETHEUS_HOST_LABEL}
      {{- end}}
    volumes_from:
      - prom-conf
    volumes:
      - prometheus-data:/prometheus
    links:
      {{- if eq .Values.RANCHER_URL "" }}
      - cadvisor:cadvisor
      - node-exporter:node-exporter
      {{- end}}
      - prometheus-rancher-exporter:prometheus-rancher-exporter
    extra_hosts:
      - "rancher-server:${RANCHER_SERVER}"

  graf-db:
    tty: true
    image: infinityworks/graf-db:11
    command: cat
    volumes:
      - /var/lib/grafana/

  grafana:
    tty: true
    image: grafana/grafana:4.2.0
    {{- if ne .Values.GRAFANA_PORT "" }}
    ports:
      - ${GRAFANA_PORT}:3000
    {{- end}}
    labels:
      io.rancher.sidekicks: graf-db
      {{- if ne .Values.GRAFANA_HOST_LABEL "" }}
      io.rancher.scheduler.affinity:host_label: ${GRAFANA_HOST_LABEL}
      {{- end}}
    volumes_from:
       - graf-db
    links:
      - prometheus:prometheus
      - prometheus-rancher-exporter:prometheus-rancher-exporter

  prometheus-rancher-exporter:
    tty: true
    labels:
      io.rancher.container.create_agent: true
      io.rancher.container.agent.role: environment
    image: infinityworks/prometheus-rancher-exporter:v0.22.52
