name: GoCD
description: |
  GoCD Stack (server and agents) Branched by I&Co
version: 17.3.0-ico-10001
category: Continuous Integration
maintainer: "Sebastien Langoureaux <linuxworkgroup@gmail.com>"
license: Apache License
projectURL: https://www.gocd.io/
