.catalog:
  name: Splunk Light
  version: 6.5.0
  description: Operational Intelligence in its lightest form
  minimum_rancher_version: 1.3.6
  questions:
    - variable: PUBLIC
      label: Publish UI Port?
      description: Choose to allow direct access to the UI port.  Otherwise externally configure access eg via a load balancer.
      required: true
      default: true
      type: boolean
    - variable: PUBLIC_PORT
      label: Splunk UI Port to Publish
      description: Normally 8000. Ignored if publish is false, otherwise required.
      default: 8000
      required: false
      type: int
    - variable: AFFINITY_HOST_LABEL
      label: Host Affinity
      description: Control the hosts on which the splunk runs. Will run on any available host if left blank.
      type: string
      default: splunk=true
forwarder:
  scale: 1
  start_on_create: true
splunk:
  scale: 1
  start_on_create: true
